### ISSUE TITLE
pydantic should be less than 2

### ISSUE THREAD

**Issue by mhamri** [pylakey/aiotdlib#115]
https://github.com/pylakey/aiotdlib/blob/4c1390aad0bbb85dbb552810b5c519fd0ccb9bf0/pyproject.toml#L30C9-L30C23

I wonder the last release added a check to make sure it's smaller than version2. but requirement is asking for less than v3. i found this contradicting

**Comment by pylakey** [comment]
The package wouldn't be installed this way. But for some simple projects it's possible to downgrade pydantic to continue using aiotdlib. 

Perhaps you are right and it was not a great idea) but in the next release it will be fixed (as in main branch already)
