### ISSUE TITLE
API doesn't return latest messages from channels

### ISSUE THREAD

**Issue by Eldellano** [pylakey/aiotdlib#121]
Hi all. I use aiotdlib to read posts from telegram channels and noticed that the client.api.search_public_chat method in the last_message block does not return the last message.
For example, with a request dated April 15, I receive posts from April 10, although 5 days have already passed since then and many new messages have appeared in the channel.
The same situation occurs when receiving messages by date through the client.api.get_chat_message_by_date method - passing it April 15 as the date, it returns messages created no later than April 10. 
Tell me what could be the problem and how to fix it? Thank you.

**Comment by pylakey** [comment]
Plase provide a minimal reproducible code example (please do not put any credentials in your example) using latest version of library 0.23.1
