### ISSUE TITLE
ValidationError in InlineKeyboardButton

### ISSUE THREAD

**Issue by mrb0098** [pylakey/aiotdlib#136]
when i using **InlineKeyboardButton()** got  **ERROR - 1 validation error for InlineKeyboardButton type**

`inline_keyboard = []
 inline_keyboard.append([InlineKeyboardButton(text="💰My Wallet",type_=InlineKeyboardButtonTypeCallback(data=base64.b64encode("wallet".encode("utf-8"))))])`

**Comment by pylakey** [comment]
Share your stacktrace, what exactly happens, which field failed to validate?

**Comment by mrb0098** [comment]
here you are
`- ERROR - 1 validation error for InlineKeyboardButton
type
  Field required [type=missing, input_value={'text': '💰 My Wallet...ack', data=b'd2FsbGV0')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
Traceback (most recent call last):
  File "/root/newver/newbot/lib/python3.10/site-packages/aiotdlib/client.py", line 214, in _call_handler
    await handler(self, update)
  File "/root/newver/newbot/lib/python3.10/site-packages/aiotdlib/handlers.py", line 40, in __call__
    return await self.function(client, update)
  File "/root/newver/newbot/linkbot/plugins/help_text.py", line 167, in upgrade
    inline_keyboard.append([InlineKeyboardButton(text="💰 My Wallet پول",type_=InlineKeyboardButtonTypeCallback(data=base64.b64encode("wallet".encode("utf-8"))))])
  File "/root/newver/newbot/lib/python3.10/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for InlineKeyboardButton
type
  Field required [type=missing, input_value={'text': '💰 My Wallet...ack', data=b'd2FsbGV0')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
`

**Comment by pylakey** [comment]
Try to pass `type` not `type_` argument

**Comment by mrb0098** [comment]
This worked
Thank
