### ISSUE TITLE
Why aiotdlib Docker image was deleted?

### ISSUE THREAD

**Issue by swimmwatch** [pylakey/aiotdlib#16]
Hello! Why aiotdlib Docker image was deleted?

[README.md](https://github.com/pylakey/aiotdlib#docker) contains information about Docker image. I think it needs to be updated.

**Comment by pylakey** [comment]
You are right, README needs to be updated and I will do it ASAP

**Comment by pylakey** [comment]
This docker image is not flexible. The easier way is just to add aiotdlib as dependency to your own dockerfile

**Comment by swimmwatch** [comment]
> This docker image is not flexible. The easier way is just to add aiotdlib as dependency to your own dockerfile

How can i add aiotdlib to own Dockerfile? I need to use pip? In that case don't need to install libraries?
```bash
RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libssl-dev \
    libc++-dev \
    libc++abi-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by pylakey** [comment]
You need install them as well as pip package. You can find them all in TDLib's README

**Comment by swimmwatch** [comment]
Ok, thanks
