### ISSUE TITLE
Enhancement proposal: add a non interactive alternative to ainput

### ISSUE THREAD

**Issue by truenicoco** [pylakey/aiotdlib#20]
It would be nice to add something similar to https://python-telegram.readthedocs.io/en/0.14.0/non_blocking_login.html to be able to login when console input is not an option.

EDIT: my workaround: subclassing `Client` and overriding `__auth_get_code`

**Comment by pylakey** [comment]
Your workaround is about how OOP works. Good job 👍

**Comment by truenicoco** [comment]
This does not work easily because of [name mangling](https://docs.python.org/3/tutorial/classes.html#private-variables). 

`__auth_get_code` is internally renamed `_Client__auth_get_code` by the python interpreter. A workaround is to define `self._Client__auth_get_code` in the `__init__` of a `Client` subclass, but this feels very hacky.
I think that by convention, `__` methods are meant to be "superprivate" and absolutely not subclassed. Is it really the case for `Client.__auth*` methods?
