### ISSUE TITLE
missing some updates

### ISSUE THREAD

**Issue by mrb0098** [pylakey/aiotdlib#21]
Hi
I use this package to set up my own bot
But sometimes when several people send messages to the bot at the same time or one user sends several messages to the bot, I encounter this error and the process of responding to the user by the bot stops.
In other words, the update is lost

`Task was destroyed but it is pending!
task: <Task pending name='Task-28779883' coro=<Client.__handle_update() running at /usr/local/lib/python3.10/dist-packages/aiotdlib/client.py:628> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]>>`

**Comment by mrb0098** [comment]
Is there no solution?

**Comment by pylakey** [comment]
Could you provide a minimal working code example with this issue?
