### ISSUE TITLE
Running multiple clients

### ISSUE THREAD

**Issue by lorien** [pylakey/aiotdlib#38]
Hello!
Quick question.
Do you think there could be any issues if I create multiple client instances in one program? Of course I will use different auth credentials and different storage locations for each client instance.

**Comment by pylakey** [comment]
I think there will no any problem, but some of tdlib users noticed rising RAM consumption when tdlib instance is running too long.

If you will meet any problem please let me know

**Comment by pylakey** [comment]
Some explanations: https://github.com/tdlib/td/issues/1704
