### ISSUE TITLE
Unable to send documents larger than 2 GB

### ISSUE THREAD

**Issue by mrb0098** [pylakey/aiotdlib#39]
Hello
I use `send_document` function to send documents in Telegram
But when the file size is more than 2 GB, the function throws an exception, but no error is displayed in the log.

```
try :
    await client.send_document(
                    chat_id=my_chat_id,
                    document=mydocument,
                    caption=mycaption)
        
except Exception as e:
    #No information is displayed
    logger.error(e)
```

**Comment by mrb0098** [comment]
any solution until now ?!

**Comment by pylakey** [comment]
Files larger than 2 GB are not supported for usual accounts in telegram. You can send them only with Telegram premium. Current version of library doesn't support telegram premium yet. So you are not able to send files >2GB with aiotdlib.

Actually, I don't now why error is  not logged properly in your example, try to add exc_info=True
