### ISSUE TITLE
if I want to run the script with two clients at the same time, I get an error

### ISSUE THREAD

**Issue by yaischyk** [pylakey/aiotdlib#40]
**It's my code:**

![Знімок екрана 2022-08-11 о 15 24 14](https://user-images.githubusercontent.com/98265143/184132718-cac20e76-b7de-40f4-aaa8-20f7c6868b6a.png)

**Error:**
_[Client.cpp:285] Receive must not be called simultaneously from two different threads, but this has just happened. Call it from a fixed thread, dedicated for updates and response processing._
Aborted

How can I run multiple clients?

**Comment by pylakey** [comment]
Aiotdlib do not support multiple clients with single tdlib instance for now
