### ISSUE TITLE
Add tests?

### ISSUE THREAD

**Issue by samuelcolvin** [pylakey/aiotdlib#43]
Hi, this question is quite selfish, I'd like to use this repo among others for smoke testing new pydantic releases, see https://github.com/pydantic/pydantic/discussions/4359. According to [this](https://sourcegraph.com/notebooks/Tm90ZWJvb2s6MTU1MQ==#by-repo-d7df30cd-e39d-4deb-9fb6-9eaeef4bf511) this repo has lots of pydantic imports, hence why I came here.

Would you consider adding tests to this repo, I don't know if there's a dummy api for telegram, otherwise you could create mock endpoints for unit tests.

Do you have an existing strategy for testing?

**Comment by pylakey** [comment]
Hi, I don't have any strategy for testing yet.

Telegram needs you to be authorized to use API, so it's quite a problem to run tests automatically, in GitHub actions for example. But mock endpoints could help in this situation.

I will think about adding tests. Any PRs are welcome

**Comment by samuelcolvin** [comment]
Thanks for considering it.

In the absence of tests, I'd love it if you could test [`v1.10.0a1`](https://github.com/pydantic/pydantic/releases/tag/v1.10.0a1), and let us know if you see any breaking changes?
