### ISSUE TITLE
But how can I register new users without manually entering the registration code?

### ISSUE THREAD

**Issue by hwmbing11** [pylakey/aiotdlib#5]
This project is great. Thank the author

But how can I register new users without manually entering the registration code?
And first_name and last_name
It is to pass the verification code to aiotdlib by passing parameters

**Comment by hwmbing11** [comment]
This project is great. Thank the author

But how can I register new users without manually entering the registration code?

**Comment by pylakey** [comment]
You can inherit aiotdlib.Client class and override its methods with your logic. 

Something like this:

```python
import aiotdlib


class CustomClient(aiotdlib.Client):
    async def __auth_get_code(self) -> str:
        # TODO: Make http request or read code from file
        pass

    async def __auth_get_first_name(self) -> str:
        # TODO: Make http request or read first_name from file
        pass

    async def __auth_get_last_name(self) -> str:
        # TODO: Make http request or read last_name from file
        pass

    async def __auth_get_password(self) -> str:
        # TODO: Make http request or read password from file
        pass

```

**Comment by hwmbing11** [comment]
Thank you very much for your reply
