### ISSUE TITLE
pypi packaging improvements

### ISSUE THREAD

**Issue by truenicoco** [pylakey/aiotdlib#50]
There are some problems with the pypi package:

- the .tar.gz actually contains linux/amd64 and darwin/arm64 binaries for tdlib but are supposed to be source only
- the .whl is tagged architecture "none", but actually only works on linux/amd64 and darwin/arm64

I know this is in the README, but since I have a [project depending on aiotdlib](https://sr.ht/~nicoco/slidge/) and proper multiarch packaging would be great for it, I might submit a MR to have this properly done via github actions. Would you accept it? (not promising any timeline here ;))

**Comment by pylakey** [comment]
Sure! Feel free to open any PR 😉

**Comment by truenicoco** [comment]
Poetry has not stable API to do this, but here's an example of a project that hacked something to do it anyway:

https://github.com/sdispater/pendulum/blob/master/pyproject.toml#L67

I have not attempted it yet, but I guess we can try to do it the same way.

@pylakey did you apply some patches in your tdlib fork?
In other words, do we have to use your fork of tdlib or can we just checkout to a specific commit from the main tdlib source?

**Comment by pylakey** [comment]
I've only added binary building with github actions to tdlib fork. No patches are aplied to original codebase

**Comment by truenicoco** [comment]
Did you close because of inactivity or because you're against the idea? I planned on giving this a new try this summer. This lib is great and I'm happy to use it, but having non-conform wheels on PyPI makes it very complicated to publish software depending on it. Providing tdlib binaries for all platforms is probably complicated, but packaging it in a way that makes it possible to build from source when build dependencies are available would be excellent… would you accept a PR in this direction?

**Comment by pylakey** [comment]
When PR is ready, let's get back to this discussion)
