### ISSUE TITLE
More priority for older downloads

### ISSUE THREAD

**Issue by mrb0098** [pylakey/aiotdlib#52]
According to the documents [in this file](https://github.com/pylakey/aiotdlib/blob/beab642821cce72e2fa689ed26ea81fe3cc5ab0a/aiotdlib/api/functions/download_file.py) (line 20)
If 2 downloads start with the same priority
The file that started earlier (older) gets lower priority
And the newer file will be downloaded first
Is there a way to reverse the queue?
It means that the file that started earlier will be served and downloaded sooner ([FCFS](https://en.wikipedia.org/wiki/FIFO_(computing_and_electronics)))

**Comment by pylakey** [comment]
I think your question is related to [tdlib](https://github.com/tdlib/td) repository. Aiotdlib is just a wrapper around it written in python.
