### ISSUE TITLE
OSError: Image not found

### ISSUE THREAD

**Issue by mariusorani** [pylakey/aiotdlib#53]
Hi, 

when i try to run the script, it throws an error.

`OSError: dlopen(/Users/morhan/Documents/Projekte/Automation/pytelegram/env/lib/python3.9/site-packages/aiotdlib/tdlib/libtdjson_darwin_amd64.dylib, 6): image not found`

Any Idea?

**Comment by pylakey** [comment]
Mac OS build is provided only for Apple Silicon. You have to build tdlib yourself in order to use with Intel. 

You can clone aiotdlib repo and use build_mac.sh script to build currently supported tdlib version. But if you want you can look at build instruction in tdlib repository and follow it.

**Comment by mariusorani** [comment]
Cloning the repo and building the tdlib solved the problem. :) Thank you!
