### ISSUE TITLE
Using 'aiotdlib_generator' with 1.8.8 tl schema

### ISSUE THREAD

**Issue by kurkl** [pylakey/aiotdlib#57]
Hi. I'm trying to parse actual data from [tdlib/td/master/td/generate/scheme/td_api.tl](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl)
Parsing seems to work, but there may be a problem with code generation.
https://github.com/pylakey/aiotdlib/blob/def90ae8706582b9b67f5bce6237fe1bc5a7a2dc/aiotdlib_generator/parser/parser.py#L13
Change to `DEFAULT_TD_API_SCHEME_URL=https://raw.githubusercontent.com/tdlib/td/master/td/generate/scheme/td_api.tl`

`poetry run aiotdlib_generator`

`from aiotdlib import Client`
`ImportError: cannot import name 'InternalLinkType' from partially initialized module 'aiotdlib.api.types.internal_link_type' (most likely due to a circular import)`
This is the only problem type, if you remove it, then everything works

General question, are you planning to support new versions of TDLib?

**Comment by pylakey** [comment]
Yes I am planning to support the newest version of library. But I feel this will actually need big refactoring in types package to fix circular imports problem and do not break backward compatibility with older versions of aiotdlib. 

If you have any ideas, feel free to comment here or open PR.

**Comment by pylakey** [comment]
Feel free to open a PR with support of the newest tdlib version

**Comment by joshms123** [comment]
You mentioned in a previous comment that it would need refactoring. I am just wondering how this is going.

**Comment by pylakey** [comment]
It is not started yet. Unfortunately, I have no time to do it now
