### ISSUE TITLE
dont work example - ImportError

### ISSUE THREAD

**Issue by gotomadness** [pylakey/aiotdlib#6]
i do 
pip install aiotdlib (in env)
aiotdlib==0.13.0
Python 3.9.5

main.py copy-paste as in first example
python main.py

result
ImportError: cannot import name 'UpdateChatVoiceChat' from 'aiotdlib.api' (/home/user/dir/dir/env/lib/python3.9/site-packages/aiotdlib/api/__init__.py)

I noticed that this code was here
find 'UpdateChatVoiceChat' in branch f5caf18
https://github.com/pylakey/aiotdlib/blob/f5caf18346d7d19d9aa9a3f9daa7a29f1361005d/aiotdlib/api/types/update.py

but then it disappeared, and is not defined anywhere else in the current head master 0.13.

What am I doing wrong?

**Comment by gotomadness** [comment]
In other words - where defined class is the UpdateChatVoiceChat?

**Comment by pylakey** [comment]
This bug was related to [this](tdlib/td@c69293e) TDLib's commit.

VoiceChat is renamed to VideoChat everywhere
