### ISSUE TITLE
How to catch the error of tdlib instead of exiting the program directly

### ISSUE THREAD

**Issue by hwmbing11** [pylakey/aiotdlib#7]
" [ 1][t 4][1638596870.449850320][ThemeManager.cpp:160][#1][!ThemeManager] Failed to parse chat themes from binlog: [Error : 0 : Too much data to fetch at 16] "

How should errors like this be caught? Instead of exiting the program directly

**Comment by pylakey** [comment]
This error related to tdlib. Aiotdlib only provides a wrapper for tdlib. You can try to ask your question there
