### ISSUE TITLE
BindKey failed: [Error : 400 : ENCRYPTED_MESSAGE_INVALID]

### ISSUE THREAD

**Issue by mrb0098** [pylakey/aiotdlib#75]
[ 1][t 3][1686847796.387447118][Session.cpp:401][#1][!Session:1:download#1]       BindKey failed: [Error : 400 : ENCRYPTED_MESSAGE_INVALID]

how can i fix this ?!

**Comment by pylakey** [comment]
This issue is related to official tdlib repo, try to ask there
