### ISSUE TITLE
Full stories support

### ISSUE THREAD

**Issue by itekhi** [pylakey/aiotdlib#91]
Hi! I'm starting a new project, and I would like to use your amazing library!

My project is fully based on telegram stories.
So, I noticed there are some missing methods in your `API` class, for example `getAllStories` which is listed in [`td/generate/scheme/telegram_api.tl`](https://github.com/tdlib/td/blob/master/td/generate/scheme/telegram_api.tl) at the very bottom.
Btw, I didn't understand why does your API have `deleteStory` method, but `td` has only `deleteStories`, could you explain please?)

Will you please add these missing methods to the library?

Btw, I'm amazed how well made this library is, the level of integration with Pydantic is just amazing 🤩 Good job!!

**Comment by pylakey** [comment]
https://github.com/tdlib/td/blob/master/td/generate/scheme/telegram_api.tl is the Telegram API itself, not TDLib. 

Aiotdlib is the Python wrapper around TDLib, look at the https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl instead
